FROM node:current-alpine

ARG FOLDER
ARG NOTION_TOKEN
ARG NOTION_ROOT_PAGE_ID

ENV FOLDER $FOLDER
ENV NOTION_TOKEN $NOTION_TOKEN
ENV NOTION_ROOT_PAGE_ID $NOTION_ROOT_PAGE_ID

RUN npm install
ENTRYPOINT ["npm run sync"]